map_path: /home/rq/matching_map/filtered_map.pcd  

registration_method: NDT   # pointcloud registration method

frame_filter: voxel_filter # you can chose：voxel_filter、no_filter

# local map is part of global map
# the param is the size of local map: min_x, max_x, min_y, max_y, min_z, max_z
box_filter_size: [-150.0, 150.0, -150.0, 150.0, -150.0, 150.0]
local_map_filter: voxel_filter # you can chose：voxel_filter、no_filter

# global map
global_map_filter: voxel_filter # you can chose：voxel_filter、no_filter


## param of NDT
NDT:
    res : 1.0
    step_size : 0.1
    trans_eps : 0.01
    max_iter : 30
## param of filter
voxel_filter:
    global_map:
        leaf_size: [0.9, 0.9, 0.9]
    local_map:
        leaf_size: [0.5, 0.5, 0.5]
    frame:
        leaf_size: [1.5, 1.5, 1.5]