data_path: ./  

# key frames
key_frame_distance: 2.0 # distance of near key frame

# graph_optimize
graph_optimizer_type: g2o 

use_gnss: true
use_loop_close: true

optimize_step_with_key_frame: 10000 # optimize with every "optimize_step_with_key_frame" new key frame 
optimize_step_with_gnss: 950 # optimize with every "optimize_step_with_gnss" new gnss constraint
optimize_step_with_loop: 100  # optimize with every "optimize_step_with_loop" new loop close constraint

g2o_param:
    odom_edge_noise: [0.5, 0.5, 0.5, 0.001, 0.001, 0.001] # noise: x y z yaw roll pitch
    close_loop_noise: [0.3, 0.3, 0.3, 0.001, 0.001, 0.001] # noise：x y z yaw roll pitch
    gnss_noise: [2.0, 2.0, 2.0] # noise：x y z