# registration
registration_method: NDT   # pointcloud registration method 


# the filter of current scan
frame_filter: voxel_filter # you can chose：voxel_filter、no_filter

# param of local map
key_frame_distance: 2.0 # key frame distance
local_frame_num: 20
local_map_filter: voxel_filter # you can chose：voxel_filter、no_filter


## param of NDT
NDT:
    res : 1.0
    step_size : 0.1
    trans_eps : 0.01
    max_iter : 30
## param of filter
voxel_filter:
    local_map:
        leaf_size: [0.6, 0.6, 0.6]
    frame:
        leaf_size: [1.3, 1.3, 1.3]